export const bucketList = [
    {"item": "👶 Be born", "status": 2},
    {"item": "🚶 Take first steps", "status": 2},
    {"item": "👄 Say first words", "status": 2},
    {"item": "📚 Learn to read", "status": 2},
    {"item": "🏫 Go to school", "status": 2},
    {"item": "👫 Make friends", "status": 2},
    {"item": "🎒 Survive school", "status": 2},
    {"item": "👭 Keep my best friends", "status": 2},
    {"item": "🎓 Get a Masters Degree", "status": 2},
    {"item": "💼 Get a job", "status": 2},
    {"item": "✈️ Fly in a plane", "status": 2},
    {"item": "⛵ Ride a boat", "status": 2},
    {"item": "🚂 Ride in a train", "status": 2},
    {"item": "🚁 Ride a helicopter", "status": 2},
    {"item": "🌊 See the ocean", "status": 2},
    {"item": "❄️ See snow", "status": 2},
    {"item": "🎤 Go to a concert", "status": 2},
    {"item": "⛺ Go camping", "status": 2},
    {"item": "💍 Get married", "status": 2},
    {"item": "💔 Get divorced", "status": 2},
    {"item": "🏢 Start a company", "status": 2},
    {"item": "📉 Fail at building a company", "status": 2},
    {"item": "📈 Succeed at building a company", "status": 2},
    {"item": "💰 Reach Financial Independence", "status": 2},
    {"item": "👴 Retire", "status": 2},
    {"item": "🚲 Learn to ride a bike", "status": 2},
    {"item": "🚗 Learn to drive a car", "status": 2},
    {"item": "⛵ Learn to drive a boat", "status": 2},
    {"item": "🏍️ Learn to drive a motorcycle", "status": 0},
    {"item": "🚲 Buy a bike", "status": 2},
    {"item": "🚗 Buy a car", "status": 2},
    {"item": "⛵ Buy a boat", "status": 0},
    {"item": "🚬 Start smoking", "status": 2},
    {"item": "🚭 Stop smoking", "status": 1, "done": "2023-08-28"},
    {"item": "🏍️ Buy a motorcycle", "status": 0},
    {"item": "🚑 Crash a bike", "status": 2},
    {"item": "🚑 Crash a car", "status": 2},
    {"item": "🚑 Crash a boat", "status": 1},
    {"item": "🚑 Crash a motorcycle", "status": 0},
    {"item": "🏠 Buy a house", "status": 2},
    {"item": "🏗️  Build a house", "status": 1, "start": "2022-01-01", "end": "2024-12-15"},
    {"item": "🇮🇸 Visit Iceland", "status": 2},
    {"item": "🇯🇵 Visit Japan", "status": 2},
    {"item": "🇪🇺 Visit Europe", "status": 2},
    {"item": "🇺🇸 Visit the USA", "status": 2},
    {"item": "✏️ Learn how to draw", "status": 1},
    {"item": "🎢 Ride a roller-coaster", "status": 2},
    {"item": "🎸 Play an instrument", "status": 0},
    {"item": "🎙️ Give a speech", "status": 2},
    {"item": "📰 Get in the news", "status": 2},
    {"item": "💰 Invest some money", "status": 2},
    {"item": "💰 Invest in 10 companies", "status": 2},
    {"item": "💰 Invest in 20 companies", "status": 1, "progress": 18, "goal": 20},
    {"item": "💰 Invest in 100 companies", "status": 1, "progress": 18, "goal": 100},
    {"item": "🤦‍♂️ Make a terrible mistake", "status": 2},
    {"item": "🏆 Win a trophy", "status": 2},
    {"item": "🏔️ Climb a mountain", "status": 1},
    {"item": "🏃‍♂️ Run a marathon", "status": 0},
    {"item": "💪Get in shape", "status": 0},
    {"item": "🕳️ Explore a cave", "status": 2},
    {"item": "🪂 Go paragliding", "status": 0},
    {"item": "🚣 Go rafting", "status": 0},
    {"item": "🛶 Go canoeing", "status": 2},
    {"item": "🛩️ Go skydiving", "status": 2},
    {"item": "🌋 See a volcano", "status": 2},
    {"item": "🌌 Fly in Zero Gravity", "status": 2},
    {"item": "🚀 Fly to space", "status": 0},
    {"item": "🇬🇧 Learn English", "status": 2},
    {"item": "🇩🇪 Learn German", "status": 1},
    {"item": "🇮🇸 Learn Icelandic", "status": 0},
    {"item": "🇯🇵 Learn Japanese", "status": 0},
    {"item": "💶 Make 10,000€", "status": 2},
    {"item": "💶 Make 100,000€", "status": 2},
    {"item": "💶 Make 1,000,000€", "status": 2},
    {"item": "💶 Make 10,000,000€", "status": 2},
    {"item": "💶 Make 100,000,000€", "status": 0},
    {"item": "❤️ Donate 10,000€", "status": 2},
    {"item": "❤️ Donate 100,000€", "status": 2},
    {"item": "❤️ Donate 1,000,000€", "status": 2},
    {"item": "❤️ Donate 10,000,000€", "status": 1},
    {"item": "❤️ Donate 100,000,000€", "status": 0},
    {"item": "🏞 Remove 1 ton of CO2 through DAC", "status": 2},
    {"item": "🏞 Remove 10 tons of CO2 through DAC", "status": 1, "pct": 20},
    {"item": "🏞 Remove 100 tons of CO2 through DAC", "status": 1, "progress": 2, "goal": 100},
    {"item": "🏞 Remove all the CO2 I've emitted (450 tons)", "status": 1, "progress": 2, "goal": 450},
    {"item": "🏞️ Become carbon-neutral", "status": 1},
    {"item": "🏞️ Become carbon-negative", "status": 0},
    {"item": "🌼 Plant a garden", "status": 2},
    {"item": "🌲 Plant a tree", "status": 2},
    {"item": "🌲 Plant a forest", "status": 1, "pct": 15},
    {"item": "🥩 Stop eating meat during each meal", "status": 2},
    {"item": "🥕 Stop eating meat", "status": 1},
    {"item": "🔆 Produce photovoltaic electricity", "status": 2},
    {"item": "🔌 Disconnect from the grid", "status": 1},
    {"item": "🌑 See a solar eclipse", "status": 2},

    {"item": "🪣 Create my bucket list", "status": 2},
    {"item": "☑️ Complete my bucket list", "status": 0},

    {"item": "🎂 Reach age 20", "status": 2},
    {"item": "🎂 Reach age 30", "status": 2},
    {"item": "🎂 Reach age 40", "status": 1, "progress": 35, "goal": 40},
    {"item": "🎂 Reach age 50", "status": 1, "progress": 35, "goal": 50},
    {"item": "🎂 Reach age 60", "status": 1, "progress": 35, "goal": 60},
    {"item": "🎂 Reach age 70", "status": 1, "progress": 35, "goal": 70},
    {"item": "🎂 Reach age 80", "status": 1, "progress": 35, "goal": 80},
    {"item": "🎂 Reach age 90", "status": 1, "progress": 35, "goal": 90},
    {"item": "🎂 Reach age 100", "status": 1, "progress": 35, "goal": 100},
    {"item": "⚰️ Die", "status": 0},
];